"""add_thumbnail_url_to_bookmarks

Revision ID: 257ac2d3ebd6
Revises: d1873c708280
Create Date: 2026-04-22 15:57:40.371665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257ac2d3ebd6'
down_revision: Union[str, Sequence[str], None] = 'd1873c708280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('thumbnail_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'thumbnail_url')
    # ### end Alembic commands ###
